site_name: 2024.1-MeasureSoftGram-DOC

repo_name: "2024.1-MeasureSoftGram-DOC"
repo_url: "https://github.com/fga-eps-mds/2024.1-MeasureSoftGram-DOC"

theme:
  name: material
  language: "pt"
  logo: "assets/logo.svg"
  favicon: "assets/logo.svg"
  palette:
    primary: blue

nav:
  - Início: index.md
  - Plano e Monitoramento:
      - Comunicação: planejamento/comunicacao.md
      - Ferramentas: planejamento/ferramentas.md
      - Heatmap de horários: planejamento/horarios.md
      - Tabela de Conhecimentos: planejamento/conhecimentos.md
      - Custos: planejamento/custos.md
      - Plano de Riscos: planejamento/riscos.md
      - Plano de Qualidade: planejamento/qualidade.md
  - Produto:
      - Lean Inception: produto/lean-inception.md
      - Documento de Identidade Visual: idv/identidade-visual.md
      - Planejado X Realizado: produto/planejado-realizado.md
  - Documentos do Projeto:
      - Arquitetura: planejamento/arquitetura.md
      - Metodologias: planejamento/metodologias.md
      - EAP: planejamento/eap.md
  - Sprints:
      - Sprint 0:
          - Review: sprints/sprint0/review.md
          - Sprint: sprints/sprint0/sprint.md
  - Guia de contribuição:
      - Código de Conduta: guia-de-contribuicao/codigo-de-conduta.md
      - Politica de Commits: guia-de-contribuicao/politica-de-commits.md
      - Politica de Branches: guia-de-contribuicao/politica-de-branch.md
  - Manual de instalação:
      - Service: manual-de-instalacao/service.md
      - Front: manual-de-instalacao/front.md
      - Action: manual-de-instalacao/action.md
      - CLI: manual-de-instalacao/cli.md

  - Post-Mortem: post-mortem/post-mortem.md
