site_name: 2024.1-MeasureSoftGram-DOC

repo_name: '2024.1-MeasureSoftGram-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-MeasureSoftGram-DOC'

theme:
  name: material
  palette:
    primary: black

nav:
  - Início: index.md
  - Planejamento:
    - Heatmap de horários: planejamento/horarios.md
    - Tabela de conhecimentos: planejamento/conhecimentos.md